MDBottomNavigationItem:
                    name: "screen 6"
                    text: "Matching Page"
                    icon: 'account-cog'
                    MDScreen:
                        MDLabel:
                            text: "Recommended Page"
                            pos_hint: {"center_x": .65, "center_y": .97}
                            theme_text_color: "Custom"
                            text_color: 63/255, 63/255, 191/255, 1
                            font_size:54
